### ISSUE TITLE
문서화 작업용

### ISSUE THREAD

**Issue by kweonsikyung** [Link-Cargo/link-cargo-front#1]
## 📌 어떤 기능에 대한 개발인가요?
스프린트 문서화 작업을 위한 임시 이슈입니다.

## 🗓️ Due date
2024.05.23. ~ 2024.05.24.

## ✅ Check List

- [x] 담당자 등록
- [x] 라벨 등록
- [x] DDL 체크

**Comment by donghyuun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [스프린트 프로세스 문서화](https://trello.com/c/YquHwqnh/11-%EC%8A%A4%ED%94%84%EB%A6%B0%ED%8A%B8-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EB%AC%B8%EC%84%9C%ED%99%94)
